### ISSUE TITLE
Default owner of ZKTree is hardcoded to an address I don't own

### ISSUE THREAD

**Issue by escottalexander** [nzmpi/ZkTree-extension-se2#1]
This is a really neat build. You have done a great job of providing clear directions on how to use it. My one issue is this:

In `extension/packages/hardhat/deploy/01_deploy_ZkTree.ts`
I see that you have hardcoded the owner:
```
  const owner = "0xd2aad578798Af2457Bba973b2b35e8DEA6b3d7a7"; 
```
Seems like it might be a better experience for developers if this was set to the deployer or at least if you mentioned in the README that it needs to be replaced before deploying.

**Comment by nzmpi** [comment]
Thank you, @escottalexander!
It actually was `owner = msg.sender`. But the deployer in the script and my burner wallet were different, so I just hard-coded it. I will fix it after the hackathon ends.
